name: Maven version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ '0.3.0', '0.4.0' ]

    name: Maven ${{ matrix.maven }} sample

    steps:
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@< version >
      with:
        java-version: 8
        maven-version: ${{ matrix.maven }}

    - run: mvn -V ...
