name: Maven-version
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: maven:3.3-jdk-8
      options: --user root
    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v3
